image: Visual Studio 2017

platform:
  - x64

install:
  - cmmd: echo "Downloading conan..."
  - cmmd: set PATH=%PATH%;%PYTHON%/Scripts/
  - cmmd: pip.exe install conan
  - cmmd: conan user # Create the conan data directory
  - cmmd: conan --version

build_script:
  - cmmd: mkdir build
  - cmmd: cd build
  - cmmd: conan install ..
  - cmmd: conan build ..

test_script:
  - cmmd: cd bin
  - cmmd: encryption_test.exe
