
variables:
    CONAN_USERNAME: "matt1795"
    CONAN_REFERENCE: "multiformats/0.1"
    CONAN_CHANNEL: "testing"
    CONAN_UPLOAD: "https://api.bintray.com/conan/matt1795/public-conan"

.build-template: &build-template
    before_script:
        - sudo pip install --upgrade conan_package_tools
        - conan remote add ${REMOTE_NAME} ${CONAN_UPLOAD}
        - conan user -p ${CONAN_PASSWORD} -r ${REMOTE_NAME} ${CONAN_USERNAME}
        - conan --version
    script:
        - python build.py
        - conan create . ${CONAN_USERNAME}/${CONAN_CHANNEL}
        - conan upload ${CONAN_REFERENCE}@${CONAN_USERNAME}/${CONAN_CHANNEL} -r ${REMOTE_NAME}

gcc-4.9:
    image: conanio/gcc49
    variables:
        CONAN_GCC_VERSIONS: "4.9"
    <<: *build-template

gcc-5:
    image: conanio/gcc5
    variables:
        CONAN_GCC_VERSIONS: "5"
    <<: *build-template

gcc-6:
    image: conanio/gcc6
    variables:
        CONAN_GCC_VERSIONS: "6"
    <<: *build-template

gcc-7:
    image: conanio/gcc7
    variables:
        CONAN_GCC_VERSIONS: "7"
    <<: *build-template

gcc-8:
    image: conanio/gcc8
    variables:
        CONAN_GCC_VERSIONS: "8"
    <<: *build-template

clang-3.9:
    image: conanio/clang39
    variables:
        CONAN_CLANG_VERSIONS: "3.9"
    <<: *build-template

clang-4.0:
    image: conanio/clang40
    variables:
        CONAN_CLANG_VERSIONS: "4.0"
    <<: *build-template

clang-5.0:
    image: conanio/clang50
    variables:
        CONAN_CLANG_VERSIONS: "5.0"
    <<: *build-template

clang-6.0:
    image: conanio/clang60
    variables:
        CONAN_CLANG_VERSIONS: "6.0"
    <<: *build-template

clang-7.0:
    image: conanio/clang70
    variables:
        CONAN_CLANG_VERSIONS: "7.0"
    <<: *build-template

clang-7.1:
    image: conanio/clang71
    variables:
        CONAN_CLANG_VERSIONS: "7.1"
    <<: *build-template

